### ISSUE TITLE
Spotfleet default keyName   

### ISSUE THREAD

**Issue by guan840912** [pahud/cdk-spot-one#1]
I am excited to try awesome `cdk-spot-noe` , but my account , did have this key !!!  `aws-pahud`

https://github.com/pahud/cdk-spot-one/blob/541b5ec78c160b699a9720daed3a7a8525f739fe/src/spot.ts#L139

**Comment by pahud** [comment]
Thanks. Will fix it later today.

**Comment by pahud** [comment]
Just released v0.3.0 and this issue should be fixed.
