### ISSUE TITLE
Idea: vend "ec2-connect.sh" and other tools

### ISSUE THREAD

**Issue by eladb** [pahud/cdk-spot-one#19]
Instead of instructing users to copy & paste this script, you can just put it under `bin/` and then users will be able to run it through:

    npx ec2-connect INSTANCE

You can take it one step further and vend scripts that will do the whole thing:

```
#!/bin/bash
set -euo pipefail
cdk deploy --outputs-file /tmp/cdk-spot-one-outputs.json
instance_id="$(node -p "require('/tmp/cdk-spot-one-outputs.json').SpotFleetInstanceId")"
npx ec2-connect $instance_id
```

You'd need to have `SpotFleet` construct auto-define the `CfnOutput` named `SpotFleetInstanceId`.

**Comment by pahud** [comment]
Closing this issue.

Now we can connect with `npx ec2-connect` like:

```
npx ec2-connect i-01f827ab9de7b93a9
```
