### ISSUE TITLE
Expose the underlying ec2 instance for easy access granting

### ISSUE THREAD

**Issue by jgoux** [pahud/cdk-spot-one#515]
Hello 👋 ,

I need to grant the ec2 instance created through the `SpotInstance` class access to other AWS resources (bucket, secret manager...)

Right now the `SpotInstance` class doesn't have the ec2 instance in its properties. It would be great to have it so we can do : 

```ts
const spotInstance = new SpotInstance(...);
mySecret.grandRead(spotInstance.instance);
```

I thought about using the exposed `instanceId` but cdk doesn't have a `fromLookup` method for ec2 instances.

**Comment by stephanrauh** [comment]
@pahud I've got the same problem. Would you mind to add the variable to the `SpotInstance` object?

**Comment by stephanrauh** [comment]
@pahud Here's what to do:

```typescript
export class SpotInstance extends SpotOne {
  readonly instanceId?: string;
  readonly instanceType?: string;
  readonly spotInstance!: ec2.Instance; // <<<< new!

  constructor(scope: Construct, id: string, props: SpotInstanceProps = {}) {
    super(scope, id, props);

    this.spotInstance = new ec2.Instance(this, 'SpotInstance', { // <<<< new!
```
