### ISSUE TITLE
Fleet Task timed out

### ISSUE THREAD

**Issue by allamand** [pahud/cdk-spot-one#67]
Hello, 

I tried to follow the deployment on "eu-west-1" region, but I got an error when deploying

```
11:42:11 AM | CREATE_FAILED        | AWS::CloudFormation::CustomResource   | Fleet/SpotFleetInstances/Default
Failed to create resource. Error: 2020-09-25T09:42:05.893Z 9ac43baa-24e9-48ed-bd6f-c1b861f237ac Task timed out after 60.06 seconds
```

This is the code I used 

```
import * as cdk from '@aws-cdk/core';
import * as ec2 from '@aws-cdk/aws-ec2';
import * as spotone from 'cdk-spot-one';

export class MyStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpc = spotone.VpcProvider.getOrCreate(this)

    const fleet = new spotone.SpotFleet(this, 'Fleet', {
      vpc,
      blockDuration: spotone.BlockDuration.SIX_HOURS,
      defaultInstanceType: new ec2.InstanceType('m5.large'),
      
    });
    fleet.expireAfter(cdk.Duration.hours(6));
  }
}
```

and

```
import 'source-map-support/register';
import * as cdk from '@aws-cdk/core';
import { MyStack } from '../lib/my-stack';

const env = {
    region: process.env.CDK_DEFAULT_REGION ? process.env.CDK_DEFAULT_REGION: "eu-west-1",
    account: process.env.CDK_DEFAULT_ACCOUNT ? process.env.CDK_DEFAULT_ACCOUNT: "xxx",
}
const app = new cdk.App();
new MyStack(app, 'MyStack', { env });
```

**Comment by pahud** [comment]
Looks like the default instance type `m5.large` has no spot capacity available in `eu-west-1` hence the handler times out.

Let me see if we can improve the error message.

<img width="1406" alt="圖片" src="https://user-images.githubusercontent.com/278432/94258370-5322ff80-ff5f-11ea-8133-7fe179123dd7.png">

**Comment by pahud** [comment]
closes with https://github.com/pahud/cdk-spot-one/commit/2995b620a6a49334b1b2e285a99df6f2e99fb195

**Comment by pahud** [comment]
[v0.6.35](https://www.npmjs.com/package/cdk-spot-one) released with the fix to display verbose error message.

Please use this npm version and try again. If you are deploying to `eu-west-1`, you can try other instance types as `m5.large` spot capacity seems to be temporarily unavailable.
