### ISSUE TITLE
Is possible to change the default commands to optional when using custom AMI?

### ISSUE THREAD

**Issue by minchao** [pahud/cdk-spot-one#93]
The default commands of instance user data install ssm agent and docker.
But when switch to custom AMI, it may be unnecessary.

https://github.com/pahud/cdk-spot-one/blob/3d4ff3329703eca2c393ece0e235f91e49d529e5/src/spot.ts#L262-L269

Reasons:

* Not everyone needs Docker
* There is already an `additionalUserData` to add new commands
* Make it possible to support community AMI (e.g. Ubuntu)

**Comment by pahud** [comment]
Hi, 

Yes,  it makes sense. The original design of `cdk-spot-one` is to create an Amazon Linux 2 EC2 Spot with docker and SSM session manager ready.  However, it would be great to support custom AMI such as Ubuntu.

I believe we can determine if `props.customAmiId`, we just do not add the commands.

What do you think?

**Comment by minchao** [comment]
Thanks, this will be very useful.

**Comment by pahud** [comment]
0.6.49 released with this feature now
https://www.npmjs.com/package/cdk-spot-one
